# Generated by Django 2.1.5 on 2019-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20191101_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='title',
            new_name='building1',
        ),
        migrations.AddField(
            model_name='map',
            name='building2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
