# Generated by Django 2.1.5 on 2019-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20191107_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building1', models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], max_length=255)),
                ('building2', models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], max_length=255)),
                ('building3', models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], max_length=255)),
            ],
        ),
    ]
