# Generated by Django 2.1.5 on 2019-11-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='building4',
            field=models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='map',
            name='building5',
            field=models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], default='', max_length=255),
        ),
    ]
