# Generated by Django 2.1.5 on 2019-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20191108_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='building4',
            field=models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building5',
            field=models.CharField(choices=[('budig', 'Budig Hall'), ('wescoe', 'Wescoe Hall'), ('snow', 'Snow Hall'), ('leep', 'LEEP2'), ('learned', 'Learned Hall'), ('eaton', 'Eaton Hall')], max_length=255),
        ),
    ]
