# Generated by Django 2.1.5 on 2019-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20191117_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='building1',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall'], ['Kansas Union', 'Kansas Union'], ['Integrated Science Building (ISB)', 'Integrated Science Building (ISB)'], ['Eaton Hall', 'Eaton Hall'], ['Snow Hall', 'Snow Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building2',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall'], ['Kansas Union', 'Kansas Union'], ['Integrated Science Building (ISB)', 'Integrated Science Building (ISB)'], ['Eaton Hall', 'Eaton Hall'], ['Snow Hall', 'Snow Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building3',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall'], ['Kansas Union', 'Kansas Union'], ['Integrated Science Building (ISB)', 'Integrated Science Building (ISB)'], ['Eaton Hall', 'Eaton Hall'], ['Snow Hall', 'Snow Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building4',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall'], ['Kansas Union', 'Kansas Union'], ['Integrated Science Building (ISB)', 'Integrated Science Building (ISB)'], ['Eaton Hall', 'Eaton Hall'], ['Snow Hall', 'Snow Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building5',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall'], ['Kansas Union', 'Kansas Union'], ['Integrated Science Building (ISB)', 'Integrated Science Building (ISB)'], ['Eaton Hall', 'Eaton Hall'], ['Snow Hall', 'Snow Hall']], max_length=255),
        ),
    ]
