# Generated by Django 2.1.5 on 2019-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20191118_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='building1',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building2',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building3',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building4',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall']], max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='building5',
            field=models.CharField(choices=[['Wescoe Hall', 'Wescoe Hall'], ['Budig Hall', 'Budig Hall'], ['LEEP2', 'LEEP2'], ['Learned Hall', 'Learned Hall'], ['Fraser Hall', 'Fraser Hall']], max_length=255),
        ),
    ]
