# Generated by Django 2.2.6 on 2019-10-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='DistanceCalculator',
        ),
    ]
