# Generated by Django 2.2.6 on 2019-11-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191031_0204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistanceCalculator',
            new_name='Distance',
        ),
    ]
