# Generated by Django 2.2.6 on 2019-11-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191101_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distance',
            new_name='Map',
        ),
    ]
