# Generated by Django 2.1.5 on 2019-11-18 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191101_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('year_in_school', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='GRADUATE', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_rated', models.CharField(choices=[('EECS101', 'EECS 101'), ('EECS168', 'EECS 168'), ('EECS140', 'EECS 140'), ('EECS210', 'EECS 210'), ('EECS268', 'EECS 268')], default='EECS101', max_length=20)),
                ('class_difficulty_level', models.CharField(choices=[('one', 'Super Easy'), ('two', 'Easy'), ('three', 'Average'), ('four', 'Hard'), ('five', 'Super Hard')], default='Super Easy', max_length=20)),
                ('class_hours_spent', models.CharField(choices=[('choice1', '0 to 3'), ('choice2', '3 to 6'), ('choice3', '6 to 9'), ('choice4', '9 to 12'), ('choice5', 'over 12')], default='0 to 3', max_length=20)),
                ('rater_grade', models.CharField(choices=[('g0', 'Prefer not to disclose'), ('g1', 'Fail or drop'), ('g2', 'D'), ('g3', 'C'), ('g4', 'B'), ('g5', 'A')], default='Prefer not to disclose', max_length=20)),
                ('class_exams_num', models.IntegerField()),
                ('class_hw', models.CharField(max_length=50)),
                ('class_comments', models.CharField(max_length=300)),
                ('class_overall', models.CharField(choices=[('one', 'I am so sorry for you'), ('two', 'Get ready for a hard semester'), ('three', 'You will be fine'), ('four', 'Interesting class'), ('five', 'Best class ever')], default='I am so sorry for you', max_length=20)),
            ],
        ),
    ]
